services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  php:
    image: php:8.2-fpm
