services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    container_name: app
    volumes:
      - ./:/var/www/doskaObnawleniya
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "5355:80"
    volumes:
      - ./:/var/www/doskaObnawleniya
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: doskaObnawleniya
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel_phpmyadmin2
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_data:
